name: Add existing app or test app

on:
  workflow_dispatch:
    inputs:
      url:
        description: Direct Download Url of .app or .zip file
        required: true
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: 'N'
defaults:
  run:
    shell: PowerShell

jobs:
  initialization :
    runs-on: windows-latest
    outputs:
      telemetryScope: ${{ steps.init.outputs.telemetryScope }}
    steps:
      - id: init
        uses: PooyaKharamesh/AL-Go-Actions/InitWorkflow@main
        with: 
          eventId : "DO0090"

  update:
    runs-on: windows-latest
    needs : [ initialization ]
    steps:
      - name: Add existing app
        uses: PooyaKharamesh/AL-Go-Actions/AddExistingApp@main
        with:
          parentTelemetryScope: ${{ needs.initialization.outputs.telemetryScope }}
          url: ${{ github.event.inputs.url }}
          directCommit: ${{ github.event.inputs.directCommit }}

  postProcess :
    runs-on: windows-latest
    needs : [ initialization , update ]
    steps:
      - name: Finalizing the workflow
        id : postProcess
        uses: PooyaKharamesh/AL-Go-Actions/workflowpostprocess@main
        with: 
          eventId : "DO0090"
          telemetryScope : ${{ needs.initialization.outputs.telemetryScope }}          
