name: Create a new app

on:
  workflow_dispatch:
    inputs:
      name:
        description: Name
        required: true      
      publisher:
        description: Publisher
        required: true
      idrange:
        description: ID range (from..to)
        required: true
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: "N"

defaults:
  run:
    shell: PowerShell
jobs:
  initialization :
    runs-on: windows-latest
    outputs:
      telemetryScope: ${{ steps.init.outputs.telemetryScope }}
      correlationId: ${{ steps.init.outputs.correlationId }} 
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}   
    steps:
      - name: init
        uses: PooyaKharamesh/AL-Go-Actions/InitWorkflow@main
        with: 
          workflowName : "CreateApp"
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"

  createApp:
    runs-on: windows-latest
    needs : [ initialization ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read settings
        uses: PooyaKharamesh/AL-Go-Actions/ReadSettings@main
        with:
          get: type

      - name: Creating a new app
        uses: PooyaKharamesh/AL-Go-Actions/CreateApp@main
        with:
          type: ${{ env.type }}
          name: ${{ github.event.inputs.name }}
          publisher: ${{ github.event.inputs.publisher }}
          idrange: ${{ github.event.inputs.idrange }}
          directCommit: ${{ github.event.inputs.directCommit }}

  postProcess :
    runs-on: windows-latest
    needs : [ initialization , createApp ]
    steps:
      - name: finish
        run: write-host "testing ${{needs.initialization.outputs.telemetryScope}} and ${{ steps.initialization.outputs.correlationId }}"
      - run: echo ${{needs.initialization.outputs.output1}} ${{needs.initialization.outputs.output2}}

