name: Create a new test app

on:
  workflow_dispatch:
    inputs:
      name:
        description: Name
        required: true
        default: '<YourAppName>.Test'         
      publisher:
        description: Publisher
        required: true
      idrange:
        description: ID range
        required: true
        default: '50000..99999'  
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: 'N'

defaults:
  run:
    shell: PowerShell

jobs:
  initialization :
    runs-on: windows-latest
    outputs:
      telemetryScope: ${{ steps.init.outputs.telemetryScope }}
    steps:
      - id: init
        uses: PooyaKharamesh/AL-Go-Actions/InitWorkflow@main
        with: 
          workflowName : "DO0095"

  update:
    runs-on: windows-latest
    needs : [ initialization ]

    steps:
      - name: Creating a new test app
        uses: PooyaKharamesh/AL-Go-Actions/CreateApp@main
        with:
          parentTelemetryScope: ${{ needs.initialization.outputs.telemetryScope }}
          type: 'Test App'
          publisher: ${{ github.event.inputs.publisher }}
          name: ${{ github.event.inputs.name }}
          idrange: ${{ github.event.inputs.idrange }}
          directCommit: ${{ github.event.inputs.directCommit }}
